### ISSUE TITLE
How to send int or short?

### ISSUE THREAD

**Issue by Whirlwind** [dreese/FastSocket#16]
I can not find that how to send integer or short integer. Please tell me that, thanks...

**Comment by dreese** [comment]
Sorry for the delay. Just saw this.

**Comment by dreese** [comment]
So the basic idea is to convert the int or short to an array of bytes, and then send that using `sendBytes:count:`.

```
byte[] a = new byte[2];
a[0] = (byte) (x & 0xff);
a[1] = (byte) ((x >> 8) & 0xff);
[socket sendBytes:a count:2];
```

On the other side, you'd need to reverse the process. Some systems expect the bytes in a certain order.

Way too late. Don't know how I missed this. Sorry!
