### ISSUE TITLE
timeout cannot be for less than 1 second

### ISSUE THREAD

**Issue by brintoneng** [dreese/FastSocket#21]
- (BOOL)setTimeout:(long)seconds   Should take a float instead of a long.  It should calculate the number of microseconds and pass those to the  `struct timeval`.

Without this functionality it's impossible to have a fast poling socket applicaiton

**Comment by dreese** [comment]
Sorry for the (huge) delay. I wasn't notified of your submission. I will take a look. This is a good suggestion.

**Comment by dreese** [comment]
This should be solved by [c623afa9485c5b2c93a58191b69d3905d04981d3].
