### ISSUE TITLE
Unable to build FastSocket on Xcode 9.0 (9A235)

### ISSUE THREAD

**Issue by lrebscher** [dreese/FastSocket#24]
**Error**
in FastSocket.m:426
`Declaration of 'select' must be imported from module 'Darwin.POSIX.sys.time' before it is required
Implicit declaration of function 'select' is invalid in C99
`

**Solution**
The following import solved the problem for me:
`#include <sys/time.h>`

Stumbled upon a solved ticket (https://github.com/blinksh/blink/issues/336) reporting the same problem in a different project.

**Comment by lrebscher** [comment]
@dreese  two pull request fixing this bug already exist, could you maybe merge one of them and deploy a new release?

**Comment by dreese** [comment]
Weird. I didn't not receive an email for your comment two days ago. I apologize for that. Will take a look.

**Comment by dreese** [comment]
There are two PRs to solve this. Looking.

**Comment by dreese** [comment]
Fixed by #22

**Comment by lrebscher** [comment]
Thank you!
